code_type: LDPC
code_n: 204
code_k: 102
standardize: True
file_extension: '.alist'
inner_code_config: MarkerCodeConfig

MarkerCodeConfig:
  marker: [0, 0, 1]
  N_c: 7
  p: 1

ConvolutionalCodeConfig:
  k: 1
  g: [5, 7]
  p: 1
  random_offset: False