model_path: Results_BCJRFORMER/11022025_155134_BCJRFORMER_channel_pi_0.0_pd_0.05_ps_0.0_LDPC_n_96_k_48_CONV_k_1_g_[5, 7]_p_1/best_model.pth

specific_model: "IdsECCTOuterModel"

inner_code_config: MarkerCodeConfig

masked_attention: true
gpu: 3

compile_model: false

test_batch_size: 256
test_batches_per_epoch: 1600


seed: 42
N_dec: 1
d_model: 16
h: 2

log_wandb: true


IDSChannelConfig:
  p_d: 0.05
  p_s: 0.05
  p_i: 0.05


InnerModelConfig:
  delta_std_multiplier: 3.5
  n_sequence_min: 1
  n_sequence_max: 1