########
# An example configuration for a model run
########

specific_model: "BCJRFormerModel"

inner_code_config: MarkerCodeConfig

epochs: 400
workers: 0

masked_attention: true
gpu: 3
dropout: 0.0
batch_size: 256
batch_accumulation: 1
batches_per_epoch: 400

lr: 0.00025
scheduler_type: 'cosine'

warmup_epochs: 100

compile_model: false

test_batch_size: 256
test_batches_per_epoch: 1600


seed: 42
N_dec: 6
d_model: 96
h: 8

log_wandb: true

save_checkpoints_every_n_epochs: 100
IDSChannelConfig:
  p_d: 0.05
  p_s: 0.05
  p_i: 0.05


InnerModelConfig:
  delta_std_multiplier: 3.5
  n_sequence_min: 3
  n_sequence_max: 3